version: '3'

services:
  git:
    environment:
      - LOCAL_USER_ID=
      - GIT_NAME= 
      - GIT_EMAIL= 
    image: local/gitbox
    command: /bin/bash
    volumes:
      - LOCAL_VOLUME:/project
